[package]
name = "aqft_core"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
nalgebra = "0.32"
num-complex = "0.4"
pyo3 = {
    version = "0.21.0",
    features = ["extension-module"]
}
numpy = "0.21"

[features]
default = []
python = ["dep:pyo3"]
